Network/TCP(흐름제어,혼잡제어)/TCP_IP_Congestion Control.md
Network/TCP(흐름제어,혼잡제어)/TCP_IP_Flow Control.md

TCP Congestion Control/Flow Control 

---

Network/UDP.md

Taekhwan
Please, let my file located in UDP directory after receiving Ricky's pull request.
Thank you!

2019-08-26 UDP added

---

Concept/github 협업하기.md

Add link of github mirroring...

Update github 협업하기.md

---

Design Pattern/Design Pattern_Adapter.md
Design Pattern/Design Pattern_Factory Method.md
Design Pattern/Design Pattern_Template Method.md

Adapter, Factory, Template Method 등 design pattern 정리

2019-10-02 [Design Pattern] Adapter & Factory & Template Method

---

Concept/[OS] System Call (Fork Wait Exec).md

운영체제의 System call의 일종인 fork, wait, exec를 정리하였습니다.

2019-10-03 [Operating System] Some System call (especially fork)

---

Database/[DB] Anomaly.md
Database/[DB] Index.md

2019-10-04 [DB] Anomaly & Index Concept Added

2019-10-04 [DB] Anomaly & Index Concept Added

---

Design Pattern/Adapter Pattern.md

중복 코드 삭제 및 오타 수정

---

Language/[java] String StringBuilder StringBuffer 차이.md

[java] String StringBuilder StringBuffer added

[java] String StringBuilder StringBuffer added

---

Web/[Web] REST API.md

2019-10-14 [Web] REST API Document Added

2019-10-14 [Web] REST API Document Added

---

Web/[Web] REST API.md

2019-10-14 [Web] REST API Add

---

Language/[Java] Intrinsic Lock.md

2019-10-15 [Java] Intrinsic Lock Added

2019-10-15 [Java] Intrinsic Lock Added

---

Language/[Java] Intrinsic Lock.md
Language/[Java] wait notify notifyAll.md

2019-10-21 [Java] wait notify notifyAll Update

2019-10-21 [Java] wait notify notifyAll Update

---

Web/[Web] REST API.md

REST API의 특징 및 `HATEOAS` 설명 추가

2019-10-21 [Web] REST API Update

---

Web/JWT(JSON Web Token).md

add JWT.md

---

Computer Science/Operation System/Semaphore & Mutex.md

Typing Error Fix

---

README.md

1. Change my name / Ricky -> GimunLee
2. Change template of 'Language'

2019-12-02 README.md Update

---

README.md

2020-01-22 README.md Update

---

Language/[java] Call by value와 Call by reference.md

* Java 함수 호출 방식에는 primitive type은 call by value, reference type은 call by reference 로 동작
* Java 함수 호출 방식은 오직 call by value로만 동작
설명하는 것이 조금 서툴러서 굉장히 긴 글을 쓰게 되었는데, Stack overflow 링크도 남겨두었습니다.
조금 수정하셔서 사용해주셨으면 좋겠습니다 :)

Update [java] Call by value와 Call by reference.md

---

Computer Science/Operation System/CPU Scheduling.md

CPU Scheduing
- 사진 정리 -> 텍스트 변환
- 추가 정리
- 기존 이미지는 링크로 첨부 (사진으로 첨부 시 내용 중복)

Update CPU Scheduling.md

---

Computer Science/Network/TCP (흐름제어혼잡제어).md

오타수정 (Multicative -> Multiplicative)

Update TCP (흐름제어혼잡제어).md

---

Computer Science/Operation System/CPU Scheduling.md

제목 CPU Scheduing 오타를  CPU Scheduling으로 변경하였습니다.😄

2020-09-09 [Operating System] CPU Scheduling Update

---

Design Pattern/Singleton Pattern.md

게으른 초기화 보단.
초기화 지연이라는 것이 더 직관적인거 같습니다 :)

2020-10-13 [Design Pattern] Singleton Pattern Update

---

Algorithm/QuickSort.md

중간 요소를 피벗으로 정하는 퀵소트 코드에 오탈자가 있는 듯 합니다

2020-10-23 [Algorithm] QuickSort Update

---

Computer Science/Software Engineering/클린코드(Clean Code) & 시큐어코딩(Secure Coding).md

Update 클린코드(Clean Code) & 시큐어코딩(Secure Coding).md 오타 수정합니다 

---

Computer Science/Network/OSI 7 계층.md

2021-03-09 [Network] OSI 7 계층 Update

---

Algorithm/QuickSort.md

인자로 제공되어야 하는 값들이 제대로 제공되어 있지 않음.

QuickSort 자바 예시코드 오류 수정

---

Computer Science/Operating System/CPU Scheduling.md

CPU 스케줄링 부분에서 비선점형 스케줄링 기법인 HRN에 대한 설명을 추가했습니다.

2021-03-27 [OS] CPU Scheduling Add

---

Language/[Javascript] Closure.md
[Javasript] Object Prototype.md

[JavaScript] closure와 object prototype 정리했습니다

Creating the new reference of javascript

---

Language/[Javascript] 데이터 타입.md

JavaScript data type 관련해서 작성했습니다!

Writing the reference of datatype in JavaScript

---

Computer Science/Operating System/PCB & Context Switcing.md

Update PCB & Context Switcing.md

---

Computer Science/Software Engineering/클린코드(Clean Code) & 시큐어코딩(Secure Coding).md

Fix 클린코드(Clean Code) & 시큐어코딩(Secure Coding).md

---

Web/CSRF & XSS.md

XSS,CSRF 의 가장 중요한 방어 방법이 빠져서 추가합니다..
PS 실제로 면접에서 질문 나왔던 내용이기도 합니다.

2022-01-14 [WEB] XSS,CSRF Update

---

Web/JWT(JSON Web Token).md

Update JWT(JSON Web Token).md

---

Computer Science/Network/대칭키 & 공개키.md

Update 대칭키 & 공개키.md

---

Algorithm/Sort_Counting.md

안녕하세요
자료 보면서 공부하다가 counting sort 코드가 이상한 부분이 있어서 수정했습니다
1. 과정 3에서 누적합을 만들어줄 때 `arr.length` -> `counting.length`
2. 과정 4에서 다시 sorted_arr에 넣어줄 때 인덱스가 `counting[arr[i]]` -> `counting[arr[i]] - 1`
좋은자료 항상 감사합니다 :)

[Algorithm] Counting sort 코드 수정

---

Computer Science/Network/UDP.md

Have added a useful resource about the Domain Name System from the scaler topics in the reference section.

Added a useful resource

---

Computer Science/Software Engineering/애자일(Agile)2.md

안녕하세요! 좋은 레포지토리를 운영해주셔서 감사합니다. 많은 도움을 받고 있습니다!🙂

2022-12-07 [Software Engineering] Agile2 Update

---

Web/Spring/[Spring Data JPA] 더티 체킹 (Dirty Checking).md

자료 너무 잘 보고 있습니다!!
더티 체킹은 내용에 있는대로 JPA를 구현한 구현체(e.g Hibernate)의 기술이고, Spring Data JPA는 스프링에서 JPA를 편하게 사용하기 위해 JPA를 한 단계 더 추상화 시킨 모듈이라고 알고 있습니다. 그래서 본문을 보고 더티 체킹이 Spring Data JPA의 기술이라고 착각할 여지가 있다고 생각해 수정합니다!
**변경사항**

2023-01-17 [JPA] 더티 체킹 (Dirty Checking) Update

---

README.md

README.md 목차 중 Database 하위의 Nomalization 항목의 오타를 Normalization으로 수정하였습니다.

2023-02-04 [Database] 오타수정Update

---

Language/[Javascript] Closure.md

2023-4-12 [JavaScript] 오타수정 Update

---

Web/React/React Fragment.md

Frament -> Fragment으로 오타 수정하였습니다.

2023-04-13 [Web] React fragment 오타 수정

---

Design Pattern/SOLID.md

`SOLID.md` 문서에 있는 오탈자들을 수정하였습니다.
- Reigster -> Register
- 예제엇 -> 예제에서

`SOLID.md` 문서에 오탈자를 수정하였습니다.

---

Computer Science/Operating System/[OS] System Call (Fork Wait Exec).md

fork 실패시 주석의 위치를 if문 바로 옆으로, 더 자연스로운 위치로 이동하였습니다.

Update [OS] System Call (Fork Wait Exec).md 주석 위치 이동

---

Computer Science/Software Engineering/Clean Code & Refactoring.md

Update Clean Code & Refactoring.md

---

Computer Science/Software Engineering/클린코드(Clean Code) & 시큐어코딩(Secure Coding).md

Typo: Update 클린코드(Clean Code) & 시큐어코딩(Secure Coding).md

---

Computer Science/Software Engineering/Fuctional Programming.md

Update Fuctional Programming.md

---

Computer Science/Data Structure/Array.md

Typo: Update Array.md

---

Computer Science/Computer Architecture/중앙처리장치(CPU) 작동 원리.md

LOAD, STA, JUMP 마이크로 명령어 연산 과정을  추가했습니다

Update 중앙처리장치(CPU) 작동 원리.md

---

Interview/Interview List.md

잘못된 경로 수정했습니다.
* 기존: (생략)/README.md#소제목
* 변경: (생략)/Interview List.md#소제목

docs: 면접 질문 목차 링크 오류 수정
